[package]
name = "static"
version = "0.1.0"
authors = ["Doug Anderson444 <douganderson444@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.1", features = [] }
keystr-client = { path = "../../crates/client" }
bs = { path = "../../../../clones/bs/crates/bs" }
multicodec = { path = "../../../../clones/bs/crates/multicodec" }
provenance-log = { path = "../../../../clones/bs/crates/provenance-log" }
getrandom = { version = "0.2", features = ["js"] }
web-sys = { version = "0.3", features = ["Window", "Location"] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
